### ISSUE TITLE
Pagination: Pagination requires jQuery.[import sequence]

### ISSUE THREAD

**Issue by Apachina** [rails/importmap-rails#121]
I have problems with import priority.

in my importmap
```
pin "jquery", to: "https://ga.jspm.io/npm:jquery@3.6.0/dist/jquery.js"
pin "paginationjs", to: "https://ga.jspm.io/npm:paginationjs@2.1.5/dist/pagination.js"
```

and in application.js

```
import jquery from 'jquery'
window.jQuery = jquery
window.$ = jquery
console.log(window.jQuery)
import 'paginationjs'
```

and code from paginationjs catch earlier than code with console.log
and I catch error in line `if (typeof $ === "undefined") {...` paginationjs

I'd appreciate any help you can give me.

**Comment by dhh** [comment]
Not familiar with the paginationjs lib. But seems to be an issue with that. You're better off finding some help there.

**Comment by rmacklin** [comment]
@Apachina Imports are hoisted, so the code won't execute in the order you are expecting (instead, both `import`s will be evaluated before the other statements). You can verify that by putting breakpoints in the first line of `jquery.js`, the first line of `pagination.js`, and the `window.jQuery = jquery` line in `application.js`:

https://user-images.githubusercontent.com/1863540/166118387-9e2ec6b5-00a9-4e70-930f-b53f902adb04.mp4

If you need `window.jQuery = jquery` to execute first (so that `pagination.js` can reference it), you'll need to ensure that `pagination.js` is loaded afterwards, either by requesting it in a subsequent `<script>` tag, or by changing it to a dynamic import: `import('paginationjs')`.
