### ISSUE TITLE
Pinning a package which is already commented has no effect

### ISSUE THREAD

**Issue by matuszewskijan** [rails/importmap-rails#164]
Assuming I have this in `config/importmap.rb`:
```ruby
# pin "react", to: "https://ga.jspm.io/npm:react@18.2.0/index.js"
```

running:
```sh
./bin/importmap pin react
```

won't append a new uncommented pin or uncomment the line. I would expect that running the `pin` command will always change the `config/importmap.rb`.

It's a border-case scenario, I've tried adding `uncomment_lines("config/importmap.rb", "#{pin}\n", verbose: false)` after https://github.com/rails/importmap-rails/blob/b93ac632e492ff483c1196f0acfb278fab8e35d8/lib/importmap/commands.rb#L31

It might cause some trouble as `uncomment_lines` will transform this:
```ruby
# for example use: pin "react", to: "https://ga.jspm.io/npm:react@18.2.0/index.js"
```
to this
```ruby
for example use: pin "react", to: "https://ga.jspm.io/npm:react@18.2.0/index.js"
```

Not sure what's the right way to handle it, I'd be happy to open PR if the `uncomment_lines` approach sounds reasonable.

**Comment by airblade** [comment]
The problem is `append_to_file` uses [insert_into_file](https://github.com/rails/thor/blob/05a79fc5de4446f37512b0aa6578940ed64b5057/lib/thor/actions/file_manipulation.rb#L198) which ultimately just checks [whether the file includes the string](https://github.com/rails/thor/blob/05a79fc5de4446f37512b0aa6578940ed64b5057/lib/thor/actions/inject_into_file.rb#L113) instead of using a regexp with an anchor to the beginning of the line.

As you say, `uncomment_lines` [accepts any characters between the comment character and the string you're looking for](https://github.com/rails/thor/blob/05a79fc5de4446f37512b0aa6578940ed64b5057/lib/thor/actions/file_manipulation.rb#L296), allowing the edge case you spotted.

I think the simplest approach is to use `gsub_file`, just as the importmap code does to [update an existing pin](https://github.com/rails/importmap-rails/blob/ad2cbb5994de7a3ff7d85d017489308bcdd738fd/lib/importmap/commands.rb#L29).  I propose:

```diff
diff --git i/lib/importmap/commands.rb w/lib/importmap/commands.rb
index 73e97ea..7f587c4 100644
--- i/lib/importmap/commands.rb
+++ w/lib/importmap/commands.rb
@@ -28,6 +28,7 @@ def pin(*packages)
         if packager.packaged?(package)
           gsub_file("config/importmap.rb", /^pin "#{package}".*$/, pin, verbose: false)
         else
+          gsub_file("config/importmap.rb", /^# pin "#{package}".*$/, pin, verbose: false)
           append_to_file("config/importmap.rb", "#{pin}\n", verbose: false)
         end
       end
```

Adding this line means the `append_to_file` line will be a noop when the package was present but commented out, which is fine.

I'd probably want to extract those two lines to an `add_pin` method to keep the `pin` method readable.

**Comment by dhh** [comment]
I think we should just output a "pinned package is already listed in importmap.rb". Feel free to open a PR for that.
