### ISSUE TITLE
files ending in `_index.js` have `index` replaced with an empty string

### ISSUE THREAD

**Issue by mylons** [rails/importmap-rails#215]
in my `config/importmap.rb` i have a chunk like this:
```ruby
pin_all_from "app/javascript/js", under: "js"
pin_all_from "app/javascript/packs", under: "packs"
```

and in `app/javascript/packs` these files:
```bash
$ ls -d app/javascript/packs/*index.js
app/javascript/packs/abi_qpcr_experiments_index.js     app/javascript/packs/cycling_conditions_index.js       app/javascript/packs/qc_ce_exo_experiment_index.js
```

and the resulting importmap in my html looks like:
```json
"packs/abi_qpcr_experiments_": "/assets/packs/abi_qpcr_experiments_index-1924998a54634a9130705d836ab9821cc85e91ae5e24a764da11453f1e886a48.js",
"packs/cycling_conditions_": "/assets/packs/cycling_conditions_index-3a06c6dfab430b457fb88a0e248e36c32a69c586c71b40ebcc6fc4ecc7749f40.js",
"packs/qc_ce_exo_experiment_": "/assets/packs/qc_ce_exo_experiment_index-53c5205c7d54cc05a38d33e96af386a61d128c79fa8d59e2e734af303d790a7f.js",
```

is this expected behavior?

**Comment by mylons** [comment]
Ah, it does appear this is happening on purpose. I'm curious why? Should I rename my files?
https://github.com/rails/importmap-rails/blob/e0c1676aba525716f657dd2c8cc128ddd8da2de8/lib/importmap/map.rb#L144

Looking at the rest of the repo it's not obvious as to why a file ending in `index` should have that removed

**Comment by dhh** [comment]
It's happening to support that library/index.js can be referenced as library.js. But it's not intended that library_index.js is transformed. Please do explore a fix!

**Comment by Caleb-T-Owens** [comment]
Breaking down the regex, it's scanning for:
- `\/?` ← Matches one or zero `/` characters
- `index` ← Matches the word index
- `$` ← Matches the end of a line

This is to try and match the following examples:
- `index.js`
- `folder/index.js`

But because it looks for 0 or 1 `/`, it also picks up `super_index.js`

I'm going to put together a PR updating this regex to `/(:\/|^)index$/` which broken down is:
- `(:` ← Start non-capturing group
  - `\/` ← Matches the `/` character
  - `|` ← OR operator
  - `^` ← Matches the start of the string
- `)` ← Close group
- `index` ← Matches the word index
- `$` ← Matches the end of a line

Which will still match
- `index.js`
- `folder/index.js`
but specifically won't match `super_index.js` because we're now require either the string to start or the character `/` right before the word `index`
