### ISSUE TITLE
Multiple importmaps

### ISSUE THREAD

**Issue by manuelmeurer** [rails/importmap-rails#240]
Maybe I'm missing something, but shouldn't it be possible to have multiple separate importmaps? :)

My app has three distinct parts/namespaces ("web" for the public marketing page, "admin" for the admin area, and "clients" for the login area for clients) and for each I'd like to have different pinned (and preloaded) modules.

Right now I'm solving it by keeping three different `Importmap::Map`s around and delegating `Rails.application.importmap` to `Current.importmap`, which loads the correct importmap for the current namespace, but that seems to be much more complicated than it should be.

I'm sure I'm not the only one that has multiple distinct namespaces in their app? :)
Is there another way to solve this?

Happy to have a stab at implementing this if it's a welcomed feature.

**Comment by deanpcmad** [comment]
I'd also like to see this. Would be very useful for splitting up public/admin JS

**Comment by sarmad90** [comment]
@manuelmeurer that's great. Let me know if you need any help in completing the PR. I would be happy to help.

**Comment by sarmad90** [comment]
@manuelmeurer I have added some comments on the PR.

**Comment by aseroff** [comment]
I +1 the need for this. 
An approach I was considering taking is keeping a single importmap (since having unnecessary pins doesn't make a significant difference), but changing the preload status based on the provided import module tag.

To illustrate: [javascript_importmap_tags](https://github.com/rails/importmap-rails/blob/f2779ee6a048d0e56c12ceb4a56b680c7ab272b2/app/helpers/importmap/importmap_tags_helper.rb#L3) expands to the importmap, the preloads, and the initial module import defined by the provided entry_point parameter. If we passed the entry_point parameter to `javascript_importmap_module_preload_tags`, we could enable the preloading to be defined by something like `pin 'admin', preload: [:admin]` in `config/importmap.rb`

**Comment by jimhj** [comment]
Definitely need this.
any progress?

**Comment by manuelmeurer** [comment]
Fixed by #253.

**Comment by henrikbjorn** [comment]
@manuelmeurer This is not fixed by #253 

This will still allow for a gem to overwrite the names of the pinned dependencies eg `pin_all_from "app/javascript/controllers", under: "controllers"`

Or to include dependencies that will interfere with each other.

I don't really get how the `preload: ['array', 'of', 'entrypoints']` is better than having `config/importmaps/application.rb` and `config/importmaps/admin.rb` etc. and then allow referencing those by name.

**Comment by manuelmeurer** [comment]
Well, #253 makes it possible to preload dependencies based on different entry points, which (for the most part) solves the same problem that multiple separate importmaps would solve. @dhh [decided that this was sufficient](https://github.com/rails/importmap-rails/pull/241#issuecomment-2351683291).

Gems that include a separate area like Mission Control Jobs should always define their own importmap IMO, as implemented in https://github.com/rails/mission_control-jobs/pull/163.

**Comment by henrikbjorn** [comment]
@manuelmeurer I don't see it as gems defining separate areas, being different from an application that have e.g a marketing frontend and an application / dashboard area.

**Comment by henrikbjorn** [comment]
Mostly because I think it is not solving a need or issue that people have.

I have taken a stab at it with https://github.com/henrikbjorn/importmap-rails/commit/ef4df9c365097dfbdb15189d17feea847d2484ad which just keep all of the normal `config/importmap.rb` configuration and cli etc. So everything works as now

But additional importmaps can be defined in `config/importmaps` and accessed via `Rails.application.importmaps.admin`

I think this strikes a balance of keeping everything simple as it is today, but also allow for more complex applications and workflows.

@dhh What do you think about that approach ?
