### ISSUE TITLE
Syntax error in map.rb

### ISSUE THREAD

**Issue by Svashta** [rails/importmap-rails#269]
I just updated importmaps to v2.0.2 and I am getting an syntax error in map.rb:45

importmap-rails-2.0.2/lib/importmap/map.rb:45: syntax error, unexpected ')'
`...s_and_directories(entry_point:), resolver:).values`

**Comment by hurricup** [comment]
Same here. ruby 3.0.6 in our case.

**Comment by Faye-Matthews** [comment]
Same issue. I'm using ruby 3.0.2 and rails 7.0.8

**Comment by kblake** [comment]
Same. Ruby 3.0.6. Rails 7.0.6

**Comment by kblake** [comment]
Looks like a fix is already on its way

https://github.com/rails/importmap-rails/pull/268

**Comment by jhawthorn** [comment]
I've just released importmap-rails 2.0.3, which should restore compatibility with Ruby 2.7/3.0 for now. 🤞

However it's most likely that future versions will not support versions of Ruby below 3.1 (and the gemspec will reflect this so not get pulled in). Ruby 3.0 has been EOL for even security updates from Ruby upstream since April of this year so it is probably time to upgrade ❤.
