### ISSUE TITLE
Uncaught SyntaxError: The requested module 'tslib' does not provide an export named 'default'

### ISSUE THREAD

**Issue by BranLiang** [rails/importmap-rails#87]
Trying to use package `@shopify/polaris` using importmap, failed to load the component and found the following messgae in the console.
```
Uncaught SyntaxError: The requested module 'tslib' does not provide an export named 'default'
```

Steps to reproduce the error:
1. Install packages using importmap
```
bin/importmap pin @shopify/polaris htm/react react-dom
```
2. Load a simple react component
```js
import ReactDOM from "react-dom"
import { html } from "htm/react"

import {AppProvider} from '@shopify/polaris'

const app = html`
  <${AppProvider}>
    Hello world
  <//>
`

ReactDOM.render(app, document.getElementById("root"))
```

Tried to search around, https://github.com/vitejs/vite/issues/1583 it looks like the suggestion is to use `tslib.es6.js`, however, according to the importmap list, it is already using the `tslib.es6.js`

```ruby
pin "tslib", to: "https://ga.jspm.io/npm:tslib@1.14.1/tslib.es6.js"
```

Also, what's more interesting is that removing the line above doesn't change anything. I will still receive the same error message. Tried to bump the `tslib` version, but doesn't work as well.

Pretty confused with this error. Does anyone have a clue here?

**Comment by guybedford** [comment]
@BranLiang unfortunately tslib version 1 exports an ES module without a default export. Note this issue was fixed in tslib 2, but it seems one of the dependencies of polaris is still stuck on the older version.

The generated import map with the `"module"` condition results in this bad import map resolving (`tslib.es6.js` being the problem):

https://generator.jspm.io/#U2NhYGBkDM0rySzJSU1hcCjOyC/ITKvUL8jPSSzKLHaw0DPQM9AtStYzBQANvBLYKgA

But if we disable the `"module"` condition (and thus using the CommonJS version converted into an ES module), it results in a working map:

https://generator.jspm.io/#U2NgYGBkDM0rySzJSU1hcCjOyC/ITKvUL8jPSSzKLHaw0DPQM9AtStYzBQAL8q7OKgA

By default import-rails will resolve with the `"module"` condition - having an option to possibly disable this in cases where it doesn't work might be one way to smooth over compat issues like this where packages don't have correct interop support (at least it would get things working in this case).

The better fix would be for polaris to upgrade to modern tslib of course.

**Comment by BranLiang** [comment]
@guybedford Thanks for the context. And yes, it worked after replacing all dependencies with those generated from website. 

Steps to fix:
1. Remove `shopify/polaris` related dependencies in the `config/importmap.rb`
2. Open `https://generator.jspm.io`, toggle off the `Module` config.
3. Copy dependencies in the website to you `config/importmap.rb`, and of course, fix the syntax.
4. 💯 

@guybedford I was blocked on step 2 a bit. Error message is below, which is opened at my normal chrome tab. In the end, I used the incognito window and it worked there. Not sure if there is any conflicts between website and chrome extensions.
![image](https://user-images.githubusercontent.com/6628202/147377062-b21b4bd6-3528-4165-ad06-7b94d1ea509c.png)

**Comment by guybedford** [comment]
@BranLiang thanks for that update - yes the Apollo Chrome extension stops native import maps from working in browsers due to that first error. The es-module-shims polyfill was updated to specifically work around this error and kick in the polyfill when it happens, it should resolve on generator.jspm.io as soon as it is updated there.
